name: Pull Request Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Print branch information
        run: git branch -av

      - run: git rev-parse HEAD^

      - name: Set the value
        id: step_one
        run: |
          echo "FOO=$(git rev-parse HEAD^)" >> $GITHUB_ENV

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.FOO }}"

      - name: echo github.event.pull_request.base.sha
        run: echo '${{ github.event.pull_request.base.sha }}'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-home-cache-cleanup: true

      - name: Upload Coverage Result
        uses: codecov/codecov-action@v3
        with:
          commit_parent: ${{ env.FOO }}
