name: Pull Request Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: echo github.event.pull_request.base.sha
        run: echo '${{ github.event.pull_request.base.sha }}'

      - name: Print commit SHAs v2
        run: |
          shaA=$(git rev-parse main)
          shaD=$(git rev-parse HEAD)
          shaB=$(git merge-base $shaD $shaA)
          shaC=$(git rev-parse HEAD)
          echo "Commit A: $shaA"
          echo "Commit B: $shaB"
          echo "Commit C: $shaC"
          echo "Commit D: $shaD"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-home-cache-cleanup: true

      - name: Upload Coverage Result
        uses: codecov/codecov-action@v3
        with:
          commit_parent: ${{ github.event.pull_request.base.sha }}
